name: Health check

on:
    push:
        branches-ignore: ["master"]

jobs:
    health_check:
        runs-on: ubuntu-latest
        steps:
            - name: check
              uses: Jtalk/url-health-check-action@v3.2
              with:
                url: https://pokedex-fso-degenone.onrender.com/health
            - name: report
              if: always()
              env:
                status_ok: ${{ job.status == 'success' }}
              run: |
                if ${{ env.status_ok }}; then
                    echo "Health check ok"
                else
                    echo "Health check fail"
                fi
