name: Hello, world!

on:
    push:
        branches: ["master"]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, world!"
            - run: date
            - run: ls -l
