name: Hello, world!

on:
    push:
        branches: ["master"]

jobs:
    print_job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, world!"

    date_job:
        runs-on: ubuntu-latest
        steps:
            - run: date

    dir_content_job:
        runs-on: ubuntu-latest
        steps:
            - run: ls -l
